import logging
import smtplib
from email.mime.text import MIMEText
from datetime import datetime
from typing import List

from config import (
    SMTP_SERVER,
    SMTP_PORT,
    SMTP_USE_SSL,
    SENDER_EMAIL,
    SENDER_AUTH_CODE,
    RECEIVER_EMAIL,
)

logger = logging.getLogger(__name__)


def _create_smtp():
    """Create SMTP connection. Uses SSL on port 465 or STARTTLS on port 587."""
    if SMTP_USE_SSL:
        return smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT, timeout=30)
    else:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT, timeout=30)
        server.starttls()
        return server


def _render_html(papers: List[dict]) -> str:
    """Render the HTML email body for a list of summarized papers."""
    date_str = datetime.now().strftime("%Y-%m-%d")
    rows = []

    for i, p in enumerate(papers, 1):
        rows.append(f"""
        <div style="margin-bottom:30px; padding-bottom:20px; border-bottom:1px solid #eee;">
            <h2 style="color:#1a1a2e; margin-bottom:8px;">{i}. {p['title']}</h2>
            <p style="color:#555; margin:4px 0;"><b>Authors:</b> {p['authors']}</p>
            <p style="margin:4px 0;"><a href="{p['url']}" style="color:#2563eb;">Paper Link</a></p>
            <p style="margin:4px 0;"><b>Relevance:</b> {p['relevance_score']}/10</p>
            <div style="margin-top:12px; padding:12px; background:#f8f9fa; border-radius:6px;">
                <p style="margin:4px 0;"><b>Core Idea:</b> {p['core_idea']}</p>
                <p style="margin:4px 0;"><b>Key Method:</b> {p['key_method']}</p>
                <p style="margin:4px 0;"><b>Why It Matters:</b> {p['why_matters']}</p>
            </div>
        </div>
        """)

    return f"""
    <html>
    <head><meta charset="utf-8"></head>
    <body style="font-family:-apple-system,BlinkMacSystemFont,sans-serif; max-width:700px; margin:0 auto; padding:20px; background:#fff;">
        <div style="background:#1a1a2e; color:#fff; padding:20px; border-radius:8px; margin-bottom:24px;">
            <h1 style="margin:0; font-size:22px;">Daily arXiv Digest — Mesh Generation</h1>
            <p style="margin:8px 0 0; opacity:0.8; font-size:14px;">{date_str} — Top {len(papers)} Papers</p>
        </div>
        {"".join(rows)}
        <p style="color:#999; font-size:12px; margin-top:30px; text-align:center;">
            Generated by Research Digest Pipeline
        </p>
    </body>
    </html>
    """


def send_digest(papers: List[dict]) -> None:
    """Render and send the HTML email digest."""
    html = _render_html(papers)
    msg = MIMEText(html, "html", "utf-8")
    msg["Subject"] = f"[arXiv Digest] Neural Mesh Generation — {datetime.now().strftime('%Y-%m-%d')}"
    msg["From"] = SENDER_EMAIL
    msg["To"] = RECEIVER_EMAIL

    logger.info("Sending digest to %s with %d papers", RECEIVER_EMAIL, len(papers))
    server = _create_smtp()
    server.login(SENDER_EMAIL, SENDER_AUTH_CODE)
    server.sendmail(SENDER_EMAIL, RECEIVER_EMAIL, msg.as_string())
    server.quit()
    logger.info("Digest sent successfully")


def send_empty_digest() -> None:
    """Send a 'no new papers' notification."""
    html = f"""
    <html>
    <head><meta charset="utf-8"></head>
    <body style="font-family:-apple-system,BlinkMacSystemFont,sans-serif; max-width:500px; margin:0 auto; padding:20px;">
        <h2>No new papers today</h2>
        <p>arXiv had no new mesh generation papers matching your queries in the past 7 days.</p>
        <p style="color:#999;">— Research Digest Pipeline, {datetime.now().strftime('%Y-%m-%d')}</p>
    </body>
    </html>
    """
    msg = MIMEText(html, "html", "utf-8")
    msg["Subject"] = f"[arXiv Digest] No New Papers — {datetime.now().strftime('%Y-%m-%d')}"
    msg["From"] = SENDER_EMAIL
    msg["To"] = RECEIVER_EMAIL

    server = _create_smtp()
    server.login(SENDER_EMAIL, SENDER_AUTH_CODE)
    server.sendmail(SENDER_EMAIL, RECEIVER_EMAIL, msg.as_string())
    server.quit()
    logger.info("Empty digest sent")
